pod 'TheAmazingAudioEngine'
pod 'pop', '~> 1.0'
pod 'SCLAlertView-Objective-C'
pod 'JGProgressHUD'
pod 'SVPullToRefresh'
pod 'Mixpanel'
pod 'Waver', '~> 0.2.0'
pod 'StreamingKit'
pod 'NSDate+TimeAgo'
pod 'PXAlertView', '~> 0.1.0'
pod 'libPhoneNumber-iOS', '~> 0.7'
